# load $XDG_CONFIG_HOME/X11/xprofile file if it exists; otherwise, load ~/.xprofile
[ -f "$XDG_CONFIG_HOME"/X11/xprofile ] && source "$XDG_CONFIG_HOME"/X11/xprofile || source ~/.xprofile

# start dwm
#exec dwm
qtile start
