#!/bin/bash

# Set country by running this command `covid country_name`
country="$1"
# Default country is Vietnam if it's not set
[ -z "${country}" ] && country="Vietnam"

LOG_FILE="/tmp/covid.log"
API_URL="https://ncovi.vnpt.vn/thongtindichbenh_v2?fbclid=IwAR2lXZ4T3pGJEHJiZqogQJVJUxbKyxe9-PYaOGTykKz8Dgxf-tvMy1jG3kE"

# Get information about Covid-19 in ${country}
info="`curl -s ${API_URL} | awk -F'}, {' '{ for (i = 1; i < 290; ++i) print $i; }' |
    grep -i "${country}" | awk -F',' '{ for (i = 1; i < 11; ++i) print $i;}'`"

array=($info)
for i in "${!array[@]}"; do
    [[ "${array[i]}" == *'"confirmed":'* ]]             && confirmed="${array[++i]}"
    [[ "${array[i]}" == *'"increase_confirmed":'* ]]    && inc_confirmed="${array[++i]}"
    [[ "${array[i]}" == *'"deaths":'* ]]                && deaths="${array[++i]}"
    [[ "${array[i]}" == *'"increase_deaths":'* ]]       && inc_deaths="${array[++i]}"
    [[ "${array[i]}" == *'"recovered":'* ]]             && recovered="${array[++i]}"
    [[ "${array[i]}" == *'"increase_recovered":'* ]]    && inc_recovered="${array[++i]}"
done

output="😷 ${confirmed}(+${inc_confirmed}), 💀 $deaths(+${inc_deaths}), 😀 $recovered(+${inc_recovered})"

# If ${confirmed} is empty (failed to crawl data), print out log file instead
if [ -z "${confirmed}" ]; then
    [ -f ${LOG_FILE} ] && cat ${LOG_FILE} 2> /dev/null ||
        printf "Failed to get covid information!"
    exit
fi

printf "${output}" > ${LOG_FILE}
printf "${output}"

exit 0
